# Uncomment the next line to define a global platform for your project
platform :ios, '13.5'

target 'test1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for test1
  pod 'RealmSwift'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Bond'
  pod 'R.swift'
end
